[platformio]
src_dir = main

[env:esp32s3]
platform = espressif32 @ ~6.9.0
board = esp32-s3-devkitc-1
framework = espidf

; Monitor Serial (baud rate padrão do bootloader do ESP32)
monitor_speed = 115200

; Decodifica Core Dump/Backtrace caso o ESP32 trave (Panic)
monitor_filters = esp32_exception_decoder

; Se o PIO não detectar a porta automaticamente, descomente e ajuste:
; upload_port = /dev/ttyUSB0   ; (Linux/Mac)
; upload_port = COM3           ; (Windows)
